### ISSUE TITLE
Error: is.list(val) is not TRUE 

### ISSUE THREAD

**Issue by devinspencer** [marinebon/sbc-shiny#1]
Hi @bbest,

Lets try out this new system. I downloaded the fixed R files from github like you taught me yesterday and when I run the code it get an error message that says is.list(val) is not TRUE 

Here is a screen shot of the error. 
![screen shot 2016-08-19 at 12 16 25 pm](https://cloud.githubusercontent.com/assets/16199682/17821496/d11041c4-6606-11e6-8283-2a86cccc5f03.png)

I have committed the code I changed to fix a previous problem but cant seem to figure this one out. 

Thanks, 
Devin!

**Comment by bbest** [comment]
Hi @devinspencer,

Good job creating an issue. When you get an error message running the shiny app locally, you can look in your RStudio Console for the full error stack pointing to where the problem lies.

```
Warning: Error in stopifnot: object 'dat' not found
Stack trace (innermost first):
    83: stopifnot
    82: modifyList
    81: DT::datatable
    80: function_list[[k]]
    79: withVisible
    78: freduce
    77: _fseq
    76: eval
    75: eval
    74: withVisible
    73: %>%
    72: exprFunc [/Users/bbest/github/sbc-shiny/server.R#36]
    71: widgetFunc
    70: func
    69: renderFunc
    68: output$table
     1: shiny::runApp
```

Which points us to line 36 of the server.R file:

``` r
  ##Generate data table
  output$table <- DT::renderDataTable({
    get_data() %>%
      DT::datatable(dat)
  })
```

The first argument of the `DT::datatable()` function is the input data frame (try `?DT::datatable`  on Console or `?datatable` if the `DT` library is already loaded (`library(DT)`), but when I piped (`%>%`) the previous line the first input is already fed into the function. So I simply removed `dat`. Now it works:

![image](https://cloud.githubusercontent.com/assets/2837257/17878123/7570bfa8-689d-11e6-9ff1-a32464a75bf6.png)

**Comment by bbest** [comment]
Hi @devinspencer, before you try this on your machine, be sure to do a git **Pull** (from Git pane in RStudio). Anytime you make changes be sure to **Commit** changes locally with a message and **Push** to Github.

**Comment by devinspencer** [comment]
Hi @bbest, I can pull from git but cannot push. I was looking at your directions https://github.com/OHI-Science/ohicore/issues/104 for this issue on an OHI Issues page but I cant get it to work. 

I have also tried using this fix but the terminal is saying my log in is denied yet I am certain it is the correct user name and password.  https://github.com/STAT545-UBC/Discussion/issues/93

When I do either of those options I get the following error in return:

remote: Permission to marinebon/sbc-shiny.git denied to devinspencer.
fatal: unable to access 'https://github.com/marinebon/sbc-shiny.git/': The requested URL returned error: 403

I am not sure if this is because I don't have particular accessibility to the marinebon repository or if it is a different problem.

**Comment by bbest** [comment]
Ah yes, needed to add the team sbc-mbon to the repository permissions. You're a member of that team so should now have the ability to push. Sorry about that.

![image](https://cloud.githubusercontent.com/assets/2837257/17912938/c21ada92-694b-11e6-9606-28c8b0e7fa1c.png)

**Comment by devinspencer** [comment]
Thanks @bbest! It works great now!
